apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectapp1-nginx-deployment
  labels:
    app: projectapp1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectapp1-nginx
  template:
    metadata:
      labels:
        app: projectapp1-nginx
    spec:
      containers:
        - name: projectapp1-nginx
          image: cstnacr1.azurecr.io/projectapp1nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: projectapp1-nginx-loadbalancer-service
  labels:
    app: projectapp1-nginx
spec:
  type: LoadBalancer
  selector:
    app: projectapp1-nginx
  ports:
    - port: 80
      targetPort: 80



